name: ${PROJECT_NAME}
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.bun
    container_name: ${PROJECT_NAME}-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OBJ_STORAGE_ADDR=${OBJ_STORAGE_ADDR}
      - OBJ_STORAGE_PORT=${OBJ_STORAGE_PORT}
      - OBJ_ACCESS_KEY=${OBJ_ACCESS_KEY}
      - OBJ_SECRET_KEY=${OBJ_SECRET_KEY}
      - OBJ_BUCKET=${OBJ_BUCKET}
      - OBJ_STORAGE_SSL=${OBJ_STORAGE_SSL}
    networks:
      - project-net

networks:
  project-net:
    name: ${PROJECT_NAME}-project-net